import type { Profile } from "./types"
import catpfp from "@/public/images/catpfp.jpeg"

export const profiles: Profile[] = [
  {
    id: "1",
    name: "Alex Johnson",
    email: "alex.johnson@example.com",
    resumeLink: "https://example.com/resume/alex",
    leetcodeProfile: "https://leetcode.com/alexj",
    githubLink: "https://github.com/alexj",
    linkedinLink: "https://linkedin.com/in/alexj",
    cpProfiles: ["https://codeforces.com/profile/alexj", "https://codechef.com/users/alexj"],
    ctfProfileLinks: ["https://ctftime.org/user/alexj"],
    kaggleLink: "https://kaggle.com/alexj",
    devfolioLink: "https://devfolio.co/@alexj",
    portfolioLink: "https://alexj.dev",
    shortBio:
      "Full-stack developer with 5 years of experience. Passionate about building scalable web applications and solving complex problems.",
    age: 28,
    college: "MIT",
    profilePic: catpfp.src,
    upvotes: 42,
  },
  {
    id: "2",
    name: "Samantha Lee",
    email: "samantha.lee@example.com",
    resumeLink: "https://example.com/resume/samantha",
    leetcodeProfile: "https://leetcode.com/samlee",
    githubLink: "https://github.com/samlee",
    linkedinLink: "https://linkedin.com/in/samlee",
    cpProfiles: ["https://codeforces.com/profile/samlee"],
    kaggleLink: "https://kaggle.com/samlee",
    portfolioLink: "https://samlee.dev",
    shortBio:
      "Machine learning engineer specializing in computer vision and NLP. Published researcher with experience in both academic and industry settings.",
    age: 26,
    college: "Stanford University",
    profilePic: catpfp.src,
    upvotes: 38,
  },
  {
    id: "3",
    name: "Miguel Rodriguez",
    email: "miguel.rodriguez@example.com",
    resumeLink: "https://example.com/resume/miguel",
    githubLink: "https://github.com/miguelr",
    linkedinLink: "https://linkedin.com/in/miguelr",
    ctfProfileLinks: ["https://ctftime.org/user/miguelr", "https://hackthebox.eu/profile/miguelr"],
    devfolioLink: "https://devfolio.co/@miguelr",
    shortBio:
      "Cybersecurity specialist and CTF enthusiast. Experienced in penetration testing, vulnerability assessment, and secure code review.",
    age: 31,
    college: "Georgia Tech",
    profilePic: catpfp.src,
    upvotes: 65,
  },
  {
    id: "4",
    name: "Priya Patel",
    email: "priya.patel@example.com",
    resumeLink: "https://example.com/resume/priya",
    leetcodeProfile: "https://leetcode.com/priyap",
    githubLink: "https://github.com/priyap",
    linkedinLink: "https://linkedin.com/in/priyap",
    cpProfiles: ["https://codeforces.com/profile/priyap", "https://codechef.com/users/priyap"],
    kaggleLink: "https://kaggle.com/priyap",
    portfolioLink: "https://priyap.dev",
    shortBio:
      "Backend developer with expertise in distributed systems and microservices architecture. Open source contributor and tech blogger.",
    age: 27,
    college: "UC Berkeley",
    profilePic: catpfp.src,
    upvotes: 51,
  },
  {
    id: "5",
    name: "David Kim",
    email: "david.kim@example.com",
    resumeLink: "https://example.com/resume/david",
    leetcodeProfile: "https://leetcode.com/davidk",
    githubLink: "https://github.com/davidk",
    linkedinLink: "https://linkedin.com/in/davidk",
    devfolioLink: "https://devfolio.co/@davidk",
    portfolioLink: "https://davidk.dev",
    shortBio:
      "Frontend developer and UI/UX enthusiast. Experienced in React, Vue, and Angular. Passionate about creating accessible and intuitive user interfaces.",
    age: 24,
    college: "Carnegie Mellon University",
    profilePic: catpfp.src,
    upvotes: 29,
  },
  {
    id: "6",
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    resumeLink: "https://example.com/resume/emma",
    githubLink: "https://github.com/emmaw",
    linkedinLink: "https://linkedin.com/in/emmaw",
    kaggleLink: "https://kaggle.com/emmaw",
    devfolioLink: "https://devfolio.co/@emmaw",
    shortBio:
      "Data scientist with a background in statistics and economics. Experienced in predictive modeling, A/B testing, and data visualization.",
    age: 29,
    college: "Harvard University",
    profilePic: catpfp.src,
    upvotes: 47,
  },
  {
    id: "7",
    name: "Raj Sharma",
    email: "raj.sharma@example.com",
    resumeLink: "https://example.com/resume/raj",
    leetcodeProfile: "https://leetcode.com/rajs",
    githubLink: "https://github.com/rajs",
    linkedinLink: "https://linkedin.com/in/rajs",
    cpProfiles: ["https://codeforces.com/profile/rajs", "https://codechef.com/users/rajs"],
    ctfProfileLinks: ["https://ctftime.org/user/rajs"],
    portfolioLink: "https://rajs.dev",
    shortBio:
      "Competitive programmer and algorithm specialist. Multiple-time ICPC finalist with experience in high-performance computing and optimization.",
    age: 23,
    college: "IIT Bombay",
    profilePic: catpfp.src,
    upvotes: 72,
  },
  {
    id: "8",
    name: "Olivia Chen",
    email: "olivia.chen@example.com",
    resumeLink: "https://example.com/resume/olivia",
    githubLink: "https://github.com/oliviac",
    linkedinLink: "https://linkedin.com/in/oliviac",
    devfolioLink: "https://devfolio.co/@oliviac",
    portfolioLink: "https://oliviac.dev",
    shortBio:
      "Mobile app developer specializing in cross-platform solutions. Experienced in React Native, Flutter, and native iOS/Android development.",
    age: 26,
    college: "University of Washington",
    profilePic: catpfp.src,
    upvotes: 33,
  },
  {
    id: "9",
    name: "James Taylor",
    email: "james.taylor@example.com",
    resumeLink: "https://example.com/resume/james",
    leetcodeProfile: "https://leetcode.com/jamest",
    githubLink: "https://github.com/jamest",
    linkedinLink: "https://linkedin.com/in/jamest",
    ctfProfileLinks: ["https://ctftime.org/user/jamest", "https://hackthebox.eu/profile/jamest"],
    kaggleLink: "https://kaggle.com/jamest",
    shortBio:
      "DevOps engineer and cloud architect. Experienced in AWS, Azure, and GCP. Passionate about infrastructure as code and CI/CD pipelines.",
    age: 32,
    college: "University of Michigan",
    profilePic: catpfp.src,
    upvotes: 56,
  },
]

